coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 5%
    patch:
      default:
        informational: true

ignore:
  - "cmd/*.go"
  - "internal/utils/http.go"
  - "internal/utils/io.go"
  - "internal/json/sjson.go"
  - "internal/utils/stack.go"
  - "internal/utils/prompts.go"