name: Go CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Install go dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./... -cover -json > TestResults.json
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
